version: "3.4"

services:
  mysql:
    image: mysql:latest
    restart: ${RESTART}
    container_name: nestjs-base_mysql
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}

  # postgres:
  #   image: postgres:latest
  #   restart: ${RESTART}
  #   container_name: nestjs-base_postgres
  #   ports:
  #     - ${POSTGRES_PORT}:5432
  #   volumes:
  #     - postgre-data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
  
  redis:
    image: redis:latest
    restart: ${RESTART}
    container_name: nestjs-base_redis
    ports:
      - ${REDIS_PORT}:6379

volumes:
  mysql-data:
  # postgre-data: